### ISSUE TITLE
Consistent units (elevation vs distance)

### ISSUE THREAD

**Issue by Synapticplastic** [ColinEberhardt/running-report-card#15]
Currently, elevation (metric) and distance (imperial) units don't match.  Have an option to select, or stay consistent within the same report

**Comment by ColinEberhardt** [comment]
Fixed by https://github.com/ColinEberhardt/running-report-card/commit/dd405ed0e0dd9d741f28c2d25a16c98dd99b7fbd - thanks for raising this issue.
